name: Deploy Status Check

on:
  push:
    branches:
      - main  # Se activa cuando se hace push a la rama main
  pull_request:
    branches:
      - main  # Se activa cuando se fusiona un pull request a la rama main

# Añade los permisos necesarios para el GITHUB_TOKEN
permissions:
  statuses: write  # Permiso para crear estados de commit

jobs:
  check-deploy-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify API status
        id: api-status
        run: |
          chmod +x ./scripts/check_api_status.sh  # Dar permisos de ejecución al script
          ./scripts/check_api_status.sh           # Ejecutar el script

      - name: Set deployment status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = "${{ steps.api-status.outputs.status }}";
            const commitSha = "${{ github.sha }}";

            if (status === "success") {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: commitSha,
                state: "success",
                context: "Deploy Status",
                description: "The API is up and running.",
              });
            } else if (status === "failed") {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: commitSha,
                state: "failure",
                context: "Deploy Status",
                description: "The API is down or returned an error.",
              });
            } else if (status === "off") {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: commitSha,
                state: "pending",
                context: "Deploy Status",
                description: "The API is off. No further action required.",
              });
            }